# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mncNFc3JAXeLYpqSp9FfmpilFskVqW8r
"""

from fastapi import FastAPI
import pandas as pd

app = FastAPI()

# Carga el CSV (asegúrate que el archivo esté en la misma carpeta que este .py)
df = pd.read_csv("df_transcripciones.csv")

@app.get("/")
def root():
    return {"message": "API de df_transcripciones.csv lista"}

@app.get("/data")
def get_data():
    """
    Devuelve todo el contenido del CSV en formato JSON
    """
    return df.to_dict(orient="records")